// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMu4KdXwMIiijBXPN6AXjXD0dMe7NCkzA',
    appId: '1:919983702313:android:db270015b035465406f738',
    messagingSenderId: '919983702313',
    projectId: 'ball-lock-v2',
    storageBucket: 'ball-lock-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bEeghBXkEvMk-bnZFnA23GhO5b51lxQ',
    appId: '1:919983702313:ios:32af8d805d6c1d3206f738',
    messagingSenderId: '919983702313',
    projectId: 'ball-lock-v2',
    storageBucket: 'ball-lock-v2.firebasestorage.app',
    iosBundleId: 'com.example.ballLockApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7AP_ucAcIk56yaHK_e9fRS5gYtaO_hU',
    appId: '1:919983702313:web:8772bb683ff45ef206f738',
    messagingSenderId: '919983702313',
    projectId: 'ball-lock-v2',
    authDomain: 'ball-lock-v2.firebaseapp.com',
    storageBucket: 'ball-lock-v2.firebasestorage.app',
    measurementId: 'G-Y88SXVMPWC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bEeghBXkEvMk-bnZFnA23GhO5b51lxQ',
    appId: '1:919983702313:ios:32af8d805d6c1d3206f738',
    messagingSenderId: '919983702313',
    projectId: 'ball-lock-v2',
    storageBucket: 'ball-lock-v2.firebasestorage.app',
    iosBundleId: 'com.example.ballLockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS7AP_ucAcIk56yaHK_e9fRS5gYtaO_hU',
    appId: '1:919983702313:web:fd52c81f5ada147106f738',
    messagingSenderId: '919983702313',
    projectId: 'ball-lock-v2',
    authDomain: 'ball-lock-v2.firebaseapp.com',
    storageBucket: 'ball-lock-v2.firebasestorage.app',
    measurementId: 'G-7M0D7TK2SF',
  );

}